### ISSUE TITLE
Can I have multiple cdylib output artifacts in a single project?

### ISSUE THREAD

**Issue by pepyakin** [rustwasm/team#95]
I've tried to set up my `Cargo.toml` as:

```toml
[[lib]]
name = "foo"
path = "src/foo.rs"

[[lib]]
name = "bar"
path = "src/bar.rs"
```

but Cargo complains

```
invalid type: map, expected a string for key `lib`
```

I know such mechanism works fine for `[[bin]]`, but for wasm32-unknown-unknown I guess I need `lib`.
